services:
  mongo:
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
    ports:
      - '27888:27017'
    volumes:
      - ./mongo/:/docker-entrypoint-initdb.d/:rw
    restart: unless-stopped